// Generates src/models.ts: plain row-type aliases (Lead = LeadModel, ...) for every Prisma model.
// Runs after `prisma generate` so the aliases always match the schema.
import { readdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const modelsDir = path.join(here, "..", "generated", "prisma", "models");
const names = readdirSync(modelsDir)
  .filter((f) => f.endsWith(".ts"))
  .map((f) => f.replace(/\.ts$/, ""))
  .sort();
const lines = [
  "// AUTO-GENERATED by scripts/model-aliases.mjs after `prisma generate`. Do not edit.",
  'import type * as M from "../generated/prisma/models";',
  "",
  ...names.map((n) => `export type ${n} = M.${n}Model;`),
  "",
];
writeFileSync(path.join(here, "..", "src", "models.ts"), lines.join("\n"));
console.log(`model aliases written for ${names.length} models`);
