/** ISO 3166-1 alpha-2 -> default IANA timezone (most populous / commercial zone). */
export const COUNTRY_DEFAULT_TZ: Record<string, string> = {
  AD: "Europe/Andorra", AE: "Asia/Dubai", AF: "Asia/Kabul", AL: "Europe/Tirane", AM: "Asia/Yerevan", AO: "Africa/Luanda",
  AR: "America/Argentina/Buenos_Aires", AT: "Europe/Vienna", AU: "Australia/Sydney", AZ: "Asia/Baku", BA: "Europe/Sarajevo",
  BD: "Asia/Dhaka", BE: "Europe/Brussels", BG: "Europe/Sofia", BH: "Asia/Bahrain", BN: "Asia/Brunei", BO: "America/La_Paz",
  BR: "America/Sao_Paulo", BS: "America/Nassau", BW: "Africa/Gaborone", BY: "Europe/Minsk", BZ: "America/Belize",
  CA: "America/Toronto", CH: "Europe/Zurich", CL: "America/Santiago", CM: "Africa/Douala", CN: "Asia/Shanghai",
  CO: "America/Bogota", CR: "America/Costa_Rica", CU: "America/Havana", CY: "Asia/Nicosia", CZ: "Europe/Prague",
  DE: "Europe/Berlin", DK: "Europe/Copenhagen", DO: "America/Santo_Domingo", DZ: "Africa/Algiers", EC: "America/Guayaquil",
  EE: "Europe/Tallinn", EG: "Africa/Cairo", ES: "Europe/Madrid", ET: "Africa/Addis_Ababa", FI: "Europe/Helsinki",
  FJ: "Pacific/Fiji", FR: "Europe/Paris", GB: "Europe/London", GE: "Asia/Tbilisi", GH: "Africa/Accra", GR: "Europe/Athens",
  GT: "America/Guatemala", HK: "Asia/Hong_Kong", HN: "America/Tegucigalpa", HR: "Europe/Zagreb", HU: "Europe/Budapest",
  ID: "Asia/Jakarta", IE: "Europe/Dublin", IL: "Asia/Jerusalem", IN: "Asia/Kolkata", IQ: "Asia/Baghdad", IR: "Asia/Tehran",
  IS: "Atlantic/Reykjavik", IT: "Europe/Rome", JM: "America/Jamaica", JO: "Asia/Amman", JP: "Asia/Tokyo", KE: "Africa/Nairobi",
  KH: "Asia/Phnom_Penh", KR: "Asia/Seoul", KW: "Asia/Kuwait", KZ: "Asia/Almaty", LB: "Asia/Beirut", LK: "Asia/Colombo",
  LT: "Europe/Vilnius", LU: "Europe/Luxembourg", LV: "Europe/Riga", LY: "Africa/Tripoli", MA: "Africa/Casablanca",
  MD: "Europe/Chisinau", ME: "Europe/Podgorica", MK: "Europe/Skopje", MM: "Asia/Yangon", MN: "Asia/Ulaanbaatar",
  MT: "Europe/Malta", MU: "Indian/Mauritius", MV: "Indian/Maldives", MX: "America/Mexico_City", MY: "Asia/Kuala_Lumpur",
  MZ: "Africa/Maputo", NA: "Africa/Windhoek", NG: "Africa/Lagos", NL: "Europe/Amsterdam", NO: "Europe/Oslo", NP: "Asia/Kathmandu",
  NZ: "Pacific/Auckland", OM: "Asia/Muscat", PA: "America/Panama", PE: "America/Lima", PH: "Asia/Manila", PK: "Asia/Karachi",
  PL: "Europe/Warsaw", PR: "America/Puerto_Rico", PT: "Europe/Lisbon", PY: "America/Asuncion", QA: "Asia/Qatar",
  RO: "Europe/Bucharest", RS: "Europe/Belgrade", RU: "Europe/Moscow", SA: "Asia/Riyadh", SE: "Europe/Stockholm",
  SG: "Asia/Singapore", SI: "Europe/Ljubljana", SK: "Europe/Bratislava", SN: "Africa/Dakar", SV: "America/El_Salvador",
  TH: "Asia/Bangkok", TN: "Africa/Tunis", TR: "Europe/Istanbul", TT: "America/Port_of_Spain", TW: "Asia/Taipei",
  TZ: "Africa/Dar_es_Salaam", UA: "Europe/Kyiv", UG: "Africa/Kampala", US: "America/New_York", UY: "America/Montevideo",
  UZ: "Asia/Tashkent", VE: "America/Caracas", VN: "Asia/Ho_Chi_Minh", ZA: "Africa/Johannesburg", ZM: "Africa/Lusaka",
  ZW: "Africa/Harare",
};

/** Normalized country name / alias -> ISO2. Keys are lowercase, punctuation removed. */
export const COUNTRY_ALIASES: Record<string, string> = {
  "united states": "US", "united states of america": "US", usa: "US", us: "US", "u s": "US", "u s a": "US", america: "US",
  "united kingdom": "GB", uk: "GB", "u k": "GB", "great britain": "GB", britain: "GB", england: "GB", scotland: "GB", wales: "GB", "northern ireland": "GB",
  canada: "CA", australia: "AU", "new zealand": "NZ", germany: "DE", deutschland: "DE", france: "FR", italy: "IT", italia: "IT",
  spain: "ES", espana: "ES", portugal: "PT", netherlands: "NL", "the netherlands": "NL", holland: "NL", belgium: "BE",
  switzerland: "CH", austria: "AT", sweden: "SE", norway: "NO", denmark: "DK", finland: "FI", ireland: "IE", poland: "PL",
  "czech republic": "CZ", czechia: "CZ", hungary: "HU", romania: "RO", bulgaria: "BG", greece: "GR", turkey: "TR", turkiye: "TR",
  russia: "RU", "russian federation": "RU", ukraine: "UA", "united arab emirates": "AE", uae: "AE", dubai: "AE", "saudi arabia": "SA",
  ksa: "SA", qatar: "QA", kuwait: "KW", bahrain: "BH", oman: "OM", jordan: "JO", israel: "IL", egypt: "EG", "south africa": "ZA",
  nigeria: "NG", kenya: "KE", morocco: "MA", ghana: "GH", pakistan: "PK", india: "IN", bangladesh: "BD", "sri lanka": "LK",
  china: "CN", "hong kong": "HK", japan: "JP", "south korea": "KR", korea: "KR", "republic of korea": "KR", taiwan: "TW",
  singapore: "SG", malaysia: "MY", thailand: "TH", indonesia: "ID", philippines: "PH", vietnam: "VN", "viet nam": "VN",
  brazil: "BR", brasil: "BR", argentina: "AR", chile: "CL", colombia: "CO", mexico: "MX", peru: "PE", venezuela: "VE",
  uruguay: "UY", ecuador: "EC", "puerto rico": "PR", jamaica: "JM", "dominican republic": "DO", "costa rica": "CR", panama: "PA",
  iceland: "IS", luxembourg: "LU", malta: "MT", cyprus: "CY", croatia: "HR", serbia: "RS", slovenia: "SI", slovakia: "SK",
  lithuania: "LT", latvia: "LV", estonia: "EE", belarus: "BY", georgia: "GE", armenia: "AM", azerbaijan: "AZ", kazakhstan: "KZ",
  uzbekistan: "UZ", nepal: "NP", maldives: "MV", mauritius: "MU", tunisia: "TN", algeria: "DZ", ethiopia: "ET", tanzania: "TZ",
  uganda: "UG", zambia: "ZM", zimbabwe: "ZW", mozambique: "MZ", namibia: "NA", botswana: "BW", senegal: "SN", cameroon: "CM",
  iraq: "IQ", iran: "IR", lebanon: "LB", afghanistan: "AF", myanmar: "MM", cambodia: "KH", brunei: "BN", mongolia: "MN",
  fiji: "FJ", bahamas: "BS", "trinidad and tobago": "TT", belize: "BZ", guatemala: "GT", honduras: "HN", "el salvador": "SV",
  bolivia: "BO", paraguay: "PY", cuba: "CU", libya: "LY", moldova: "MD", montenegro: "ME", "north macedonia": "MK",
  macedonia: "MK", albania: "AL", "bosnia and herzegovina": "BA", bosnia: "BA", andorra: "AD", angola: "AO",
};
